name: trilha_verde_esalq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  mime: ^1.0.5
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner.git
  mobile_scanner: ^3.5.2
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.2
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

  assets:
    - lib/assets/img/
    - lib/assets/bdtrilhaverde.json

# Ícones
flutter_launcher_icons:
  android: "icon_app"
  ios: true
  image_path: "lib/assets/img/logo.png"
  min_sdk_android: 21
